### ISSUE TITLE
NetApp Import Utility - Link

### ISSUE THREAD

**Issue by ArnaudAlbertini** [NetAppDocs/ontap-tools-vmware-vsphere#10]
Page: [Deployment workflow for existing users of ONTAP tools](https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/deploy/concept_installation_workflow_for_existing_users_of_ontap_tools.html)

Hello Team,

We mentioned in the document to use the tool : 
NetApp Import Utility for SnapCenter and Virtual Storage Console 

The link doesnt work, can we update it please ?

Thanks
Arnaud

**Comment by Netapp-shabaana** [comment]
Thank you for contacting us with your feedback. After your inputs are researched internally, we will determine how best to address it and update the content at the earliest.

**Comment by ntap-bmegan** [comment]
@netapp-manishc - Please update status, re-assign, or close if work is complete.

**Comment by netapp-jani** [comment]
Hi,
The NetApp Import Utility for SnapCenter and Virtual Storage Console is no longer used. The document is updated accordingly.
[Deployment workflow for existing users of ONTAP tools](https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/deploy/concept_installation_workflow_for_existing_users_of_ontap_tools.html).
