### ISSUE TITLE
Application Configuration

### ISSUE THREAD

**Issue by jagadeeshbabuchinde** [NetAppDocs/ontap-tools-vmware-vsphere#14]
Page: [Maintenance console options for ONTAP tools](https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/configure/reference_maintenance_console_of_ontap_tools_for_vmware_vsphere.html)

Starting with OTV 9.10, TLSv1 and TLSv1.1 protocols are disabled by default.
Hence the options 13 and 14 options were removed from maint console.

Please remove 13 and 14 options from Application Configuration

**Comment by netapp-pavanrk** [comment]
Thank you for your feedback. We will update the content to make sure it aligns with the options available on the ONTAP tools for VMware vSphere maintenance console.

Thank you for helping us improve the NetApp technical content. Please let us know if you have any other inputs or feedback on our documentation.

**Comment by netapp-jani** [comment]
@jagadeeshbabuchinde Steps 13 and 14 options from Application Configuration is removed from ONTAP tools for VMware vSphere 9.11. Here is the link to the page: [Overview of ONTAP tools maintenance console](https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/manage/reference_maintenance_console_of_ontap_tools_for_vmware_vsphere.html)
