### ISSUE TITLE
Update Request: Configure SRA on the SRM Appliance

### ISSUE THREAD

**Issue by ellen-netapp** [NetAppDocs/ontap-tools-vmware-vsphere#16]
Page: [Configure SRA on the SRM Appliance](https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/protect/task_configure_sra_on_srm_appliance.html)

Between steps 5 and 6, I request including a new step "Run command cd /var/log/vmware/srm to navigate to the log directory."

If customers aren't in that directory, they may not be able to find the container ID for our SRA when they follow the current step 6. It isn't clear from the current documentation which directory you need to be in.

**Comment by netapp-jani** [comment]
@ellen-netapp
Added the command after steps 5 in page: [Configure SRA on the SRM Appliance
](https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/protect/task_configure_sra_on_srm_appliance.html).
