### ISSUE TITLE
Advanced settings for NFS

### ISSUE THREAD

**Issue by KWG66** [NetAppDocs/ontap-tools-vmware-vsphere#18]
Page: [ONTAP tools for VMware vSphere Quick Start](https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/qsg.html)

How about keeping up to date with what is what....   your best practice guide states vSphere max heap should be 512 for vSPhere 6.0 and below, and 1024 for 6.3 and up...   but your ONTAP tools for vSphere states 512, and the OVA is setting the hosts at 512.     Please provide a proper recommendation and stick to it.   Customers rely on documentation, when it isn't correct time gets wasted.

**Comment by netapp-jani** [comment]
The ESXi host values are updated as per the best practices guide. Page: [ESXi host values set using ONTAP tools](https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/configure/reference_esxi_host_values_set_by_vsc_for_vmware_vsphere.htm)
