### ISSUE TITLE
Breadcrumb trail contains incorrect capitalization of product name

### ISSUE THREAD

**Issue by adamn-ntap** [NetAppDocs/ontap-tools-vmware-vsphere#2]
Page: [ONTAP tools for VMware vSphere Documentation](https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/index.html)

In the breadcrumb trail, the "t" in tools is incorrectly capitalized.

![image](https://user-images.githubusercontent.com/36739591/139236689-263fbd23-8b51-431a-8089-515d14dc1c49.png)

**Comment by Netapp-shabaana** [comment]
Thank you for contacting us with your feedback. We are addressing this issue in the upcoming refresh of ONTAP tools.

**Comment by ntap-bmegan** [comment]
I believe that this was fixed outside of this issue, perhaps when we changed the breadcrumb design. @netapp-pavanrk - Can you confirm?

![image](https://user-images.githubusercontent.com/56453501/186239299-75264a57-aa71-48fb-ac2e-a994dcf2f4ce.png)

**Comment by ntap-bmegan** [comment]
This issue has been closed due to inactivity. Any interested party can comment to reopen the issue.
