### ISSUE TITLE
Enabling VASA, step 1

### ISSUE THREAD

**Issue by mdmiller99** [NetAppDocs/ontap-tools-vmware-vsphere#25]
Page: [ONTAP tools for VMware vSphere Quick Start](https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/qsg.html)

For step 1 under Enabling VASA... the user needs to both the configured IP from the OVA deployment *and* port 9083.

**Comment by netapp-jani** [comment]
@mdmiller99 
Thank you for contacting us with your feedback. After your inputs are researched internally, we will determine how best to address it and update the content at the earliest.

Regards,
Jani

**Comment by netapp-jani** [comment]
@mdmiller99 
We discussed this internally with our engineers and arrived at the conclusion that there are no doc changes requires.
Reason: The IP address in step 1 refers to vCenter IP address. You need not configure any OTV IP/port (9083). The OTV appliance/VM will have the predefined/reserved ports (9083). When enabling VP/SRA capabilities these inputs are prefilled in UI in read only mode.  

If you have further questions, please email us at doccomments@netapp.com.
