### ISSUE TITLE
Since OTV9.11 is not specified , please correct it to ONTAP tools 9.11 （or ONTAP tools 9.10 or later）.

### ISSUE THREAD

**Issue by Wyu-2023** [NetAppDocs/ontap-tools-vmware-vsphere#26]
Page: [Deployment workflow for existing users of ONTAP tools](https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/deploy/concept_installation_workflow_for_existing_users_of_ontap_tools.html)

Since OTV9.11 is not specified below, please correct it to ONTAP tools 9.11 （or ONTAP tools 9.10 or later）.

＞To upgrade to ONTAP tools 9.10 you should be running virtual appliance 9.7P1 or later.

**Comment by netapp-jani** [comment]
@Wyu-2023 Thank you for contacting us with your feedback. After your inputs are researched internally, we will determine how best to address it and update the content at the earliest.

Regards,
Jani

**Comment by netapp-jani** [comment]
@Wyu-2023 Thank you for your feedback. The issue is addressed, the [Deployment workflow for existing users of ONTAP tools](https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/deploy/concept_installation_workflow_for_existing_users_of_ontap_tools.html) page is updated with the required details.
