### ISSUE TITLE
Configure SRA on the SRM Appliance documentation update

### ISSUE THREAD

**Issue by apordash** [NetAppDocs/ontap-tools-vmware-vsphere#27]
Page: [Configure SRA on the SRM Appliance](https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/protect/task_configure_sra_on_srm_appliance.html)

The command perl command.pl -I <va-IP> administrator <va-password> needs to be updated to perl command.pl -I <otv-IP> administrator <otv-password> or perl command.pl -I <sra-IP> administrator <sra-password>

Customers get confused by <va-IP> and think this is their vCenter IP

**Comment by netapp-jani** [comment]
@apordash, thank you for contacting us with your feedback. After your inputs are researched internally, we will determine how best to address it and update the content at the earliest.

Regards,
Jani

**Comment by netapp-jani** [comment]
@apordash, we have updated the page to clear the confusion. Please check page: [Configure SRA on the SRM Appliance](https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/protect/task_configure_sra_on_srm_appliance.html)

Regards,
Jani

**Comment by apordash** [comment]
Hey Jani,

Thank you for updating this document. But another part that confuses customers is the <va-password> in the perl command.

perl command.pl -I <otv-IP> administrator <va-password>

Instead of <va-password> could we change this to <sra-password> or <otv-password>

Thanks,

Adam Pordash
Technical Support Engineer
Technical Support Center, part of the NetApp Customer Support Delivery

***@***.******@***.***>
My normal working hours are:
Monday-Friday, 9:00 a.m. - 6:00 p.m. EST
***@***.***<https://www.credly.com/badges/3201a66b-3f30-41ac-bcfb-21bd0d247fbc/public_url> ***@***.*** <https://www.credly.com/badges/db366d50-4858-41c0-b92c-7e81d9974103/public_url>  ***@***.*** <https://www.credly.com/badges/a5d2fb10-319b-4420-a842-5ed8bf7ca489/public_url>

For technical assistance on a new or existing case, please call:
* US & Canada 888-4-NETAPP // * EMEA/Europe  00-800-44-638277 // * Asia/Pacific  800-8008-0800

You may also get Support on the Web at http://mysupport.netapp.com<http://mysupport.netapp.com/>.

Everyone in the NetApp Technical Support Center is committed to providing the highest level of customer satisfaction.

If you believe that the level of support can be improved, please contact my manager, Dwight Cranford, at ***@***.******@***.***>

[NetApp logo]<http://www.netapp.com/us/>

[Facebook]<http://www.facebook.com/NetApp?REF_SOURCE=ems-facebook>[Twitter]<http://twitter.com/#netapp?REF_SOURCE=ems-twitter>[Linked In]<http://www.linkedin.com/groups/NetApp-111681/about?REF_SOURCE=ems-linkedin>[YouTube]<http://www.youtube.com/user/NetAppTV?REF_SOURCE=ems-youtube>[Slideshare]<http://www.slideshare.net/NetApp?REF_SOURCE=ems-slideshare>[Community]<https://communities.netapp.com/welcome?REF_SOURCE=ems-cty>
#netapp

**Comment by netapp-jani** [comment]
@apordash  <va-password> is changed to <otv-password>. Can you please check and let us know if we can close this issue. Thanks.
