### ISSUE TITLE
Unclear port requirements

### ISSUE THREAD

**Issue by matalve** [NetAppDocs/ontap-tools-vmware-vsphere#29]
Page: [Port requirements for VSC](https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/deploy/reference_port_requirements_for_vsc.html)

I'm not a native english speaker but the instructions and Description fields make this article confusing. Please make this a bit clearer.
Some thoughts I have:

443
* Description says vCenter and storage systems listens, but instructions says to open bidirectionally. Which is it?
   - Possible follow-up question: In what cases will the vcenter and storage system contact the ONTAP Tools appliance on port 443?

8143
* Instructions says to open this bidirectionally, but description says it is only listening. Which is it?
* Bidirectionally with what exactly?

**Comment by netapp-jani** [comment]
@matalve thank you for contacting us with your feedback. After your inputs are researched internally, we will determine how best to address it and update the content at the earliest.

Regards,
Jani

**Comment by netapp-jani** [comment]
@matalve Thank you for your feedback. 
We have updated the port information on page [Port requirements for VSC](https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/deploy/reference_port_requirements_for_vsc.html). Hope this helps.
