### ISSUE TITLE
Additional Permission information needed 

### ISSUE THREAD

**Issue by TechnoNotice** [NetAppDocs/ontap-tools-vmware-vsphere#30]
Page: [Configure user roles and privileges](https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/configure/task_configure_user_role_and_privileges.html)

This process only add the use to the Cluster.  Any exist VSC are not accessible. 
What permission should the newly created user be granted on a VSC for it to manage storage in the VSC?

**Comment by netapp-jani** [comment]
@TechnoNotice, thank you for contacting us with your feedback. After your inputs are researched internally, we will determine how best to address it and update the content at the earliest.

Regards,
Jani

**Comment by netapp-jani** [comment]
@TechnoNotice After discussing this issue internally with our engineers here is the resolution:
No additional permission is required, the users need to add the storage system with the user credentials. 
After creating the user, follow the steps in page [Add storage systems to VSC](https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-98/configure/task_add_storage_systems.html) to add new storage systems. Hope this helps.

**Comment by netapp-jani** [comment]
@TechnoNotice If you have further questions please send us a note on doccomments@netapp.com
