### ISSUE TITLE
Wrong URL

### ISSUE THREAD

**Issue by Myer** [NetAppDocs/ontap-tools-vmware-vsphere#34]
Page: [Deployment workflow for existing users of ONTAP tools](https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/deploy/concept_installation_workflow_for_existing_users_of_ontap_tools.html)

Wrong URL in this sentence:
"If you are going to deploy the latest release of ONTAP tools, you must see the topic **Requirements for deploying the ONTAP tools**"

Wrong: `https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/deploy/..deploy/concept_requirements_for_deploying_ontap_tools_for_vmware_vsphere.html`

Possibly Correct (but it's empty): `https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/deploy/concept_requirements_for_deploying_ontap_tools_for_vmware_vsphere.html`

**Comment by netapp-jani** [comment]
@Myer 
Thank you for contacting us with your feedback. After your inputs are researched internally, we will determine how best to address it and update the content at the earliest.

Regards,
Jani

**Comment by netapp-jani** [comment]
@Myer 
The URL is fixed. Thank you for your input.
Page: [Deployment workflow for existing users of ONTAP tools](https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/deploy/concept_installation_workflow_for_existing_users_of_ontap_tools.html)

Regards,
Jani
