### ISSUE TITLE
OTV:9083 also communication to ESXi:random 

### ISSUE THREAD

**Issue by vgeert** [NetAppDocs/ontap-tools-vmware-vsphere#35]
Page: [Port requirements for VSC](https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/deploy/reference_port_requirements_for_vsc.html)

I think we should add a requirement. 

ESXi firewall has incoming and outgoing 
A requirement should be that OTV:9083 can talk directly to ESXi since that happens on VVOLD

**Comment by netapp-jani** [comment]
@vgeert After discussing this with our internal engineering team, we have updated the port information on page [Port requirements for VSC](https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/deploy/reference_port_requirements_for_vsc.html) . Hope this helps. If you have further questions, you can drop us an email at doccomments@netapp.com
