### ISSUE TITLE
Adding SVM's directly is not supported when using VVOL datastores

### ISSUE THREAD

**Issue by vgeert** [NetAppDocs/ontap-tools-vmware-vsphere#36]
Page: [Add storage systems](https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/configure/task_add_storage_systems.html)

Adding SVM's directly is not supported when using VVOL datastores - should be added to all doc pages that include:
* adding storage
* Storage Capability profiles.

**Comment by netapp-jani** [comment]
@vgeert 
Thank you for contacting us with your feedback. After your inputs are researched internally, we will determine how best to address it and update the content at the earliest.

Regards,
Jani

**Comment by netapp-jani** [comment]
@vgeert After discussing the issue internally, we have added a note to [Add storage systems](https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/configure/task_add_storage_systems.html) and [Overview of storage capability profiles](https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/configure/concept_configure_storage_capability_profiles.html) pages. Hope this helps.

Regards,
Deena
