### ISSUE TITLE
confusing commands

### ISSUE THREAD

**Issue by vgeert** [NetAppDocs/ontap-tools-vmware-vsphere#38]
### Page URL

https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/deploy/task_upgrade_to_the_9_8_ontap_tools_for_vmware_vsphere.html

### Page title

Upgrade to the latest release of ONTAP tools

### Summary

The commands on this page suggest that you should create a new role, while it is mentioning an existing role in the description. 

It should be clear if the user should edit the already existing role and modify this role instead of creating a new role. 

security login role create *

There should be a user friendly guidance on how to perform this. 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-jani** [comment]
@vgeert 
Thank you for contacting us with your feedback. After your inputs are researched internally, we will determine how best to address it and update the content at the earliest.

Regards,
Jani

**Comment by netapp-jani** [comment]
@vgeert, The commands are updated in page: https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/deploy/task_upgrade_to_the_9_8_ontap_tools_for_vmware_vsphere.html. Hope this helps.
