### ISSUE TITLE
We should document that OTV supports VMware's SRM Shared Recovery Site Configuration

### ISSUE THREAD

**Issue by jdwnetapp** [NetAppDocs/ontap-tools-vmware-vsphere#39]
### Page URL

https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/index.html

### Page title

ONTAP tools for VMware vSphere Documentation

### Summary

We should document that OTV supports VMware's SRM Shared Recovery Site Configuration: https://docs.vmware.com/en/Site-Recovery-Manager/8.6/com.vmware.srm.install_config.doc/GUID-EBF84252-DF37-43CD-ADC8-E90F5254F315.html.  Currently we make no mention of this type of configuration in the OTV documentation.

We have a KB article that describes the procedure for setting up SRA to support such a configuration: https://kb.netapp.com/mgmt/OTV/SRA/Storage_Replication_Adapter%3A_How_to_configure_SRA_in_a_SRM_Shared_Recovery_Site

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-jani** [comment]
@jdwnetapp 
Thank you for contacting us with your feedback. After your inputs are researched internally, we will determine how best to address it and update the content at the earliest.

Regards,
Jani

**Comment by netapp-jani** [comment]
@jdwnetapp 

We have added the reference to the KB article in page [Configure Storage Replication Adapter for SAN environment](https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/protect/task_configure_storage_replication_adapter_for_san_environment.html).
Hope this helps. 
If you are an internal NetApp user, please raise Jira for future comments.

Thank you once again for your valuable input.
