### ISSUE TITLE
Typos in shell commands to clean the vsphere cache

### ISSUE THREAD

**Issue by vperezva** [NetAppDocs/ontap-tools-vmware-vsphere#4]
This document has several typos:
ontap-tools-vmware-vsphere/deploy/task_clean_the_vsphere_cached_downloaded_plug_in_packages.adoc

1. Steps 3b and 3d are the exact same. It should be corrected so one goes to the Web client folder and the other to the HTML client folder
2. Steps 3c and 3e should mention that x.x.x.xxxx needs to be replaced with the version number of the version being removed, and not type them literally.
3. The single quote marks at the start and end of the commands in step 4 cause the commands to not run successfully. Those quote marks should not be there.

**Comment by Netapp-shabaana** [comment]
Thank you for contacting us with your feedback. After your inputs are researched internally, we will determine how best to address it and update the content at the earliest.

**Comment by ntap-bmegan** [comment]
@netapp-manishc - Please update status, re-assign, or close if work is complete.

**Comment by netapp-jani** [comment]
Comments addressed in previous release.
