### ISSUE TITLE
We should include instructions on how to use the Swagger UI

### ISSUE THREAD

**Issue by jdwnetapp** [NetAppDocs/ontap-tools-vmware-vsphere#40]
### Page URL

https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/deploy/task_deploy_ontap_tools.html

### Page title

How to deploy ONTAP tools

### Summary

With the changes in OTV 9.12, customers are having to switch from using a "friendly, easy to follow" Register.html page to building out REST API calls in the Swagger UI in order to register OTV to vCenter.

In our documentation, we simply have one line that describes this process:

"From ONTAP tools 9.12 onwards the registration of ONTAP tools with vCenter happens from the swagger page."

I believe our documentation should list out the procedure for:

1. Generating the needed vCenter API session ID
2. Using the vCenter API session ID to authenticate in Swagger UI
3. Building out the API to Register ONTAP Tools

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-jani** [comment]
@jdwnetapp 
Thank you for contacting us with your feedback. After your inputs are researched internally, we will determine how best to address it and update the content at the earliest.

Regards,
Jani

**Comment by netapp-jani** [comment]
@jdwnetapp 
After the discussing this internally with engineering. They have confirmed session ID is not require and we have added the necessary API to the documentation page [How to deploy ONTAP tools](https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/deploy/task_deploy_ontap_tools.html).
Hope this helps.
Thank you once again for your valuable input.
