### ISSUE TITLE
Flow chart diagram is missing YES / NO

### ISSUE THREAD

**Issue by jdwnetapp** [NetAppDocs/ontap-tools-vmware-vsphere#41]
### Page URL

https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/deploy/vmware_cloud_foundation_mode_deployment.html

### Page title

VMware Cloud Foundation mode of deployment for ONTAP tools

### Summary

The flowchart on this page has the following decision: "Do you want to deploy virtual appliance in VMware Cloud Foundation?". The diagram does not list YES / NO in the following decision tree.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-jani** [comment]
@jdwnetapp 
Thank you for contacting us with your feedback. After your inputs are researched internally, we will determine how best to address it and update the content at the earliest.

Regards,
Jani
