### ISSUE TITLE
VCF documentation provides no instructions of how to Add Storage for 9.12

### ISSUE THREAD

**Issue by jdwnetapp** [NetAppDocs/ontap-tools-vmware-vsphere#42]
### Page URL

https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/deploy/vmware_cloud_foundation_mode_deployment.html

### Page title

VMware Cloud Foundation mode of deployment for ONTAP tools

### Summary

In the VCF documentation we have the following one line that mentions adding storage in VCF mode:

"After the deployment is complete, you can add storage systems and create containers using REST APIs"

Adding storage in VCF mode in 9.12 involves using the Swagger UI and is not at all intuitive.  Part of the procedure involves downloading the cluster server certificate in System Manager and then having to modify that certificate so that the swagger UI accepts it.  Meaning that you have to remove carriage lines and manually insert \n after each line.

There is no way customers are going to know to do that with the certificate.  Support only figured it out by combing through burtweb.

The following article has the procedure for adding storage to OTV when VCF is enabled: https://kb.netapp.com/mgmt/OTV/SRA/Storage_Replication_Adapter%3A_How_to_configure_SRA_in_a_SRM_Shared_Recovery_Site.  The relevant section is "Add Storage to OTV from Swagger-UI".  

We need to pull this section from this KB and adapt as a general guide for adding storage in VCF enabled mode.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-jani** [comment]
@jdwnetapp 
Thank you for contacting us with your feedback. After your inputs are researched internally, we will determine how best to address it and update the content at the earliest.

Regards,
Jani

**Comment by netapp-jani** [comment]
@jdwnetapp 
We have added the KB article link in the page [VMware Cloud Foundation mode of deployment for ONTAP tools](https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/deploy/vmware_cloud_foundation_mode_deployment.html).

hope this helps.
Thank you for your valuable input.
