### ISSUE TITLE
Flowchart is missing YES / NO

### ISSUE THREAD

**Issue by jdwnetapp** [NetAppDocs/ontap-tools-vmware-vsphere#43]
### Page URL

https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/deploy/concept_installation_workflow_for_new_users.html

### Page title

Deployment workflow for new users of ONTAP tools for VMware vSphere

### Summary

Flowchart is missing YES / NO in the decision tree

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-jani** [comment]
@jdwnetapp 
Thank you for contacting us with your feedback. After your inputs are researched internally, we will determine how best to address it and update the content at the earliest.

Regards,
Jani

**Comment by netapp-jani** [comment]
@jdwnetapp, The flowchart on page [Deployment workflow for new users of ONTAP tools for VMware vSphere](https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/deploy/concept_installation_workflow_for_new_users.html) is updated.
Thank you for your feedback.
