### ISSUE TITLE
Need to improve instructions

### ISSUE THREAD

**Issue by jdwnetapp** [NetAppDocs/ontap-tools-vmware-vsphere#45]
### Page URL

https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/protect/task_enable_storage_replication_adapter.html

### Page title

Enable SRA to protect datastores

### Summary

A few suggested changes on this page:

1. Remove "Console" from Step #2.  This creates a some confusion as we have a maintenance console.  But this step is not referring to the the maintenance console.  I would simply change the line to:

"From the vSphere Client, click Menu > NetApp ONTAP tools"

2. We need to provide a URL for the SRM Appliance page in step 7a.  This would be https://<SRM>:5480
3. We need to correctly refer to the SRM appliance by it's actual name: "VMware SRM Appliance Management Interface".  So in step 7a replace the vague "SRM appliance page" with "VMware SRM Appliance Management Interface"

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-jani** [comment]
@jdwnetapp 
Thank you for contacting us with your feedback. After your inputs are researched internally, we will determine how best to address it and update the content at the earliest.

Regards,
Jani

**Comment by netapp-jani** [comment]
@jdwnetapp Thank you for your input.

The instructions on page [Enable SRA to protect datastores](https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/protect/task_enable_storage_replication_adapter.html) are now updated.
