### ISSUE TITLE
Remove old EOVS versions from this page

### ISSUE THREAD

**Issue by jdwnetapp** [NetAppDocs/ontap-tools-vmware-vsphere#46]
### Page URL

https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/protect/reference_configure_storage_replication_adapter_for_highly_scaled_environment.html

### Page title

Configure Storage Replication Adapter for highly scaled environment

### Summary

This page mentions old EOVS version 4.0 and 7.X.  I believe we should remove EOVS products from our current documentation.

Additionally I question setting storage.commandTimeout to 99,999 seconds.  If the appliance is experiencing very high CPU utilization that is driven by VP discovery, than you might have the unwelcome situation where a SRM operation runs for hours on end.  Whereas perhaps the more desired outcome is for the operation to timeout so that you can review and take steps such as disable VP discovery (if not needed).

Additionally it seems odd that we should advertise that SRA / storage needs to have a maximum timeout set.  I realize that there are several downsides to a monolithic architecture...such as VP operations stepping all over SRA operations...but I'd still like to avoid advertising that SRA / ONTAP needs unlimited time to perform operations.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-jani** [comment]
@jdwnetapp 
Thank you for contacting us with your feedback. After your inputs are researched internally, we will determine how best to address it and update the content at the earliest.

Regards,
Jani

**Comment by netapp-jani** [comment]
@jdwnetapp Thank you for your inputs.

We disused this issue with engineering internally and decided no changes are required for this. If the SRM operations take a long time to complete, then the timeout leaves the system in an incomplete state. Therefore, the recommendation stays the same for now.
If you would like to discuss further on this, please write to doccomments@netapp.com.
