### ISSUE TITLE
There is no "Export VSC Logs" option

### ISSUE THREAD

**Issue by jdwnetapp** [NetAppDocs/ontap-tools-vmware-vsphere#48]
### Page URL

https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/manage/task_collect_the_log_files.html

### Page title

Collect the log files

### Summary

This page mentions "Export VSC Logs" in several places.  This is no longer accurate.  To download OTV logs you must go to:

Settings > Export ONTAP tools for VMware vSphere Logs

There is no "Configuration > Export VSC Logs" anymore.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-jani** [comment]
@jdwnetapp 
Thank you for contacting us with your feedback. After your inputs are researched internally, we will determine how best to address it and update the content at the earliest.

Regards,
Jani

**Comment by netapp-jani** [comment]
@jdwnetapp, the [Collect the log files](https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/manage/task_collect_the_log_files.html) page is updated to reflect the correct information.
Thank you for your feedback.
