### ISSUE TITLE
Update this document to include OTV 9.12 process for access WebCLI

### ISSUE THREAD

**Issue by apordash** [NetAppDocs/ontap-tools-vmware-vsphere#51]
### Page URL

https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/configure/task_configure_user_role_and_privileges.html

### Page title

Configure user roles and privileges

### Summary

This document needs to mention how to download the ONTAP Privileges file from WebCLI when using OTV 9.12.

This KB mentions the process https://kb.netapp.com/mgmt/OTV/Virtual_Storage_Console/Virtual_Storage_Console%3A_How_to_retrieve_the_JSON_file_to_configure_user_roles_and_privileges

With OTV 9.12, users have to generate the WebCLI token from OTV's maintenance console before they can connect to WebCLI via https://{virtual_appliance_IP}:9083

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-jani** [comment]
@apordash 
Thank you for contacting us with your feedback. After your inputs are researched internally, we will determine how best to address it and update the content at the earliest.

Regards,
Jani

**Comment by jdwnetapp** [comment]
@hemanthc....this is actually a comment from Adam.  

I've reviewed this page...and I personally don't see the need to make a change for 9.12.  I'll reach out to Adam to see if he can clarify the ask.

**Comment by netapp-jani** [comment]
@apordash 
The KB article link is now provided in the document on page [Configure user roles and privileges](https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/configure/task_configure_user_role_and_privileges.html).

Thank you for your feedback.
