### ISSUE TITLE
Add extra info on the certificate

### ISSUE THREAD

**Issue by mmoret73** [NetAppDocs/ontap-tools-vmware-vsphere#53]
### Page URL

https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/qsg.html

### Page title

ONTAP tools for VMware vSphere Quick Start

### Summary

The certificate warning also comes on 7.0.3n, please adjust documentation with work-around or link to KB article.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-jani** [comment]
@mmoret73 
Thank you for contacting us with your feedback. After your inputs are researched internally, we will determine how best to address it and update the content at the earliest.

Thanks,
Jani

**Comment by netapp-jani** [comment]
@mmoret73 
Thank you for your inputs. We discussed this with engineering and decided this page does not require any updates.
The document states vCenter7.0u3e and later releases that includes 7.0.3n as well. The workaround is already documented. 
If you see a need for a KB article, please write to ng-kb-support <ng-kb-support@netapp.com>.
If you would like to discuss further on this, please write to doccomments@netapp.com.
