### ISSUE TITLE
One step is missing

### ISSUE THREAD

**Issue by Maximegnetapp** [NetAppDocs/ontap-tools-vmware-vsphere#54]
### Page URL

https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/protect/task_configure_sra_on_srm_appliance.html

### Page title

Configure SRA on the SRM Appliance

### Summary

Add as Step 1 :

1 : On vSphere client menu, click on **NetApp ONTAP tools** > **Settings** > **Administrative Settings** > **Manage Capabilities** >  **Enable Storage Replication Adapter (SRA)**

### Public issues must not contain sensitive information

- [ ] This issue contains no sensitive information.

**Comment by netapp-jani** [comment]
@Maximegnetapp 
Thank you for contacting us with your feedback. After your inputs are researched internally, we will determine how best to address it and update the content at the earliest.

Thanks,
Jani

**Comment by netapp-jani** [comment]
@Maximegnetapp The step is added to [Configure SRA on the SRM Appliance](https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/protect/task_configure_sra_on_srm_appliance.html)
