### ISSUE TITLE
Make an additional note.

### ISSUE THREAD

**Issue by pbNetApp** [NetAppDocs/ontap-tools-vmware-vsphere#55]
### Page URL

https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/manage/task_change_the_administrative_password.html

### Page title

Change the administrator password

### Summary

Hello, can you make an additional note to this "Change the administrator password." 

**Note:** If OTV environment is using Storage Replication Adapter (SRA) enabled and configured, then following the "[updating SRA Credentials](url https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/protect/task_update_sra_credentials.html)" documentation is required after changing the administrator password in OTV maintenance console also must be performed, otherwise, errors will be reported on SRM. 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-jani** [comment]
@pbNetApp 
Thank you for contacting us with your feedback. After your inputs are researched internally, we will determine how best to address it and update the content at the earliest.

Thanks,
Jani

**Comment by netapp-jani** [comment]
@pbNetApp, thank you for bringing this to our attention.
The page [Change the administrator password](https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/manage/task_change_the_administrative_password.html) is updated with a note. Hope this helps.
