### ISSUE TITLE
Please add Step 7. to Modify Storage Systems and generate certitficate

### ISSUE THREAD

**Issue by pbNetApp** [NetAppDocs/ontap-tools-vmware-vsphere#57]
### Page URL

https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/deploy/task_upgrade_to_the_9_8_ontap_tools_for_vmware_vsphere.html

### Page title

Upgrade to the latest release of ONTAP tools

### Summary

Step 7. With ONTAP Tools for VMware 9.12 authentication is done via certificate. Add either CA Signed or Self-Signed Certificate: 

a. Modify Storage Systems and Generate new self-signed certificate or add CA Signed certificate. 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-jani** [comment]
@pbNetApp 
Thank you for contacting us with your feedback. After your inputs are researched internally, we will determine how best to address it and update the content at the earliest.

Thanks,
Jani

**Comment by pbNetApp** [comment]
Thank you
