### ISSUE TITLE
please add port 8443 for Remote Plugin

### ISSUE THREAD

**Issue by pbNetApp** [NetAppDocs/ontap-tools-vmware-vsphere#58]
### Page URL

https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/deploy/reference_port_requirements_for_vsc.html

### Page title

Port requirements for ONTAP tools

### Summary

Please add port 8443 for Remote Plugin. This plugin is for inbound connections to OTV. 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-jani** [comment]
@pbNetApp
Thank you for contacting us with your feedback. After your inputs are researched internally, we will determine how best to address it and update the content at the earliest.

Thanks,
Jani

**Comment by netapp-jani** [comment]
@pbNetApp, thank you for bringing this to our attention.
The port information is updated on page: [Port requirements for ONTAP tools](https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/deploy/reference_port_requirements_for_vsc.html).
