### ISSUE TITLE
Link can be confusing

### ISSUE THREAD

**Issue by ellen-netapp** [NetAppDocs/ontap-tools-vmware-vsphere#59]
### Page URL

https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/configure/task_configure_user_role_and_privileges.html

### Page title

Configure user roles and privileges

### Summary

The link https://{virtual_appliance_IP}:9083/vsc/config/VSC_ONTAP_User_Privileges.zip mentioned in the What you’ll need section and in step 1 opens the .zip file in some browsers, instead of downloading it.

This can be a bit confusing. Can we update the steps to be the following?

1. Navigate to https://{virtual_appliance_IP}:9083/vsc/config/
2. Download the file VSC_ONTAP_User_Privileges.zip .
3. Unzip the downloaded VSC_ONTAP_User_Privileges.zip file.
4. Access System Manager
...

That proposed link would instead open the directory itself. From there, you can right-click and download the zip yourself.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-jani** [comment]
@ellen-netapp 
Thank you for contacting us with your feedback. After your inputs are researched internally, we will determine how best to address it and update the content at the earliest.

Thanks,
Jani

**Comment by netapp-jani** [comment]
@ellen-netapp, thank you for bringing this to our attention.
The steps are updated on page [Configure user roles and privileges](https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/configure/task_configure_user_role_and_privileges.html) to avoid confusion. Hope this helps.
