### ISSUE TITLE
"docker" not including on the formating on commands for steps 3 and 4

### ISSUE THREAD

**Issue by Jhon-Nieto-Netapp** [NetAppDocs/ontap-tools-vmware-vsphere#6]
Page: [Configure SRA on the SRM Appliance](https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/protect/task_configure_sra_on_srm_appliance.html)

On the commands provided 

_At the log location enter the command to get the docker ID used by SRA docker ps -l
To login to the container ID, enter command docker exec -it -u srm [container id] sh_

The docker should be included on the command formatting style, as currently it is not, the "docker" on each is not being included on the steps, and giving a different outcome than the expected.
Full command on step 3: **"docker ps -l"**
Full command on step 4: **"docker exec -it -u srm [container id] sh"**

**Comment by Netapp-shabaana** [comment]
Thank you for contacting us with your feedback. After your inputs are researched internally, we will determine how best to address it and update the content at the earliest.

**Comment by ntap-bmegan** [comment]
@netapp-manishc - Please update status, re-assign, or close if work is complete.

**Comment by netapp-jani** [comment]
Comment already addressed in previous release hence closing this.
