### ISSUE TITLE
Missing a required port in the documentation

### ISSUE THREAD

**Issue by mojjito** [NetAppDocs/ontap-tools-vmware-vsphere#63]
### Page URL

https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/deploy/reference_port_requirements_for_vsc.html

### Page title

Port requirements for ONTAP tools

### Summary

Port 8443, which is needed to be open bidirectionally, is missing from the list of network port requirements for ONTAP Tools for VMware vSphere. Please add this in. Thanks!

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-jani** [comment]
@mojjito 
Thank you for contacting us with your feedback. After your inputs are researched internally, we will determine how best to address it and update the content at the earliest.

Thanks,
Jani

**Comment by netapp-jani** [comment]
@mojjito, thank you for bringing this to our notice.
The page is updated to have the port information: [Port requirements for ONTAP tools](https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/deploy/reference_port_requirements_for_vsc.html).
