### ISSUE TITLE
Doc change to Step 1. 

### ISSUE THREAD

**Issue by apordash** [NetAppDocs/ontap-tools-vmware-vsphere#66]
### Page URL

https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/manage/task_configure_vasa_provider_to_use_ssh_for_remote_diag_access.html

### Page title

Configure remote diagnostic access

### Summary

In step 1. of this document it mentions connecting to VASA Provider via console. This confuses customers and junior support engineers and makes them think that they need to connect to the VASA Client / WebCLI ([https://<otv_ip_or_hostname>:9083).

I recommend changing this to the below instead.

1. From the vCenter Server, open a console to ONTAP Tools appliance virtual machine.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-jani** [comment]
@apordash 
Thank you for contacting us with your feedback. After your inputs are researched internally, we will determine how best to address it and update the content at the earliest.

Thanks,
Jani

**Comment by netapp-jani** [comment]
@apordash step 1 of Configure remote diagnostic access procedure is updated as per your request. Thank you for bringing this to our notice.
