### ISSUE TITLE
Default credentials option has been removed from OTV

### ISSUE THREAD

**Issue by jdwnetapp** [NetAppDocs/ontap-tools-vmware-vsphere#68]
### Page URL

https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/manage/task_set_default_credentials_for_storage_systems.html

### Page title

Set default credentials for storage systems

### Summary

This page no longer seems relevant.  In recent versions of OTV, the default credentials option has been removed from the Administrative Settings page.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-jani** [comment]
@jdwnetapp 
Thank you for contacting us with your feedback. After your inputs are researched internally, we will determine how best to address it and update the content at the earliest.

Thanks,
Jani

**Comment by netapp-jani** [comment]
@jdwnetapp, the Set default credentials for storage systems page is removed for 9.12 and 9.13 releases. Thank you for reaching out to us. NetApp employees can report doc errors using JIRA for easy tracking.
