### ISSUE TITLE
Same directory within VCSA Section

### ISSUE THREAD

**Issue by Iceman0073** [NetAppDocs/ontap-tools-vmware-vsphere#7]
Page: [Clear the vSphere cached downloaded plug-in packages](https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/deploy/task_clean_the_vsphere_cached_downloaded_plug_in_packages.html)
Within Step 3 "Remove the vSphere Client cached plug-in packages." under section "VCSA" there is the same Directory at Step "b" and at Step "d". I think this is not right?

**Comment by Netapp-shabaana** [comment]
Thank you for contacting us with your feedback. After your inputs are researched internally, we will determine how best to address it and update the content at the earliest.

**Comment by ntap-bmegan** [comment]
@netapp-soumikd - Please update status or close if work is complete.

**Comment by netapp-soumikd** [comment]
@netapp-jani Please check if this issue is fixed and update the status accordingly.

**Comment by netapp-jani** [comment]
This comment is addressed in the previous release, hence closing this issue.
