### ISSUE TITLE
Add to change the database password as well. It is required to be changed every 90days also. 

### ISSUE THREAD

**Issue by pbNetApp** [NetAppDocs/ontap-tools-vmware-vsphere#70]
### Page URL

https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/manage/task_change_the_administrative_password.html

### Page title

Change the administrator password

### Summary

Please change the document to also reflect the database password needing to be changed every 90days also. 

In the maintenance console: 

"The message appears Administrator and Database password about to expire. Please change it!"

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-jani** [comment]
@pbNetApp 
Thank you for contacting us with your feedback. After your inputs are researched internally, we will determine how best to address it and update the content at the earliest.

Thanks,
Jani

**Comment by netapp-jani** [comment]
@pbNetApp, Added the info that the password needs to be changed every 90 days in [Change the administrator password](https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/manage/task_change_the_administrative_password.html) page.
