### ISSUE TITLE
This directory structure no longer exists? So updating credentials instructions need to be updated to reflect how to remove these config files

### ISSUE THREAD

**Issue by pbNetApp** [NetAppDocs/ontap-tools-vmware-vsphere#71]
### Page URL

https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/protect/task_update_sra_credentials.html

### Page title

Update SRA credentials

### Summary

This directory structure no longer exist. Please get with the engineering team to provide updated documentation. 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-jani** [comment]
@pbNetApp 
Thank you for contacting us with your feedback. After your inputs are researched internally, we will determine how best to address it and update the content at the earliest.

Thanks,
Jani

**Comment by netapp-jani** [comment]
This issue is resolved, the directory structure information is added to the 'Update SRA credentials' page
