### ISSUE TITLE
Update perl.pl command to place single quotes around OTV administrator password value

### ISSUE THREAD

**Issue by DrKeno** [NetAppDocs/ontap-tools-vmware-vsphere#72]
### Page URL

https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/protect/task_configure_sra_on_srm_appliance.html

### Page title

Configure SRA on the SRM Appliance

### Summary

Step 10 has this value:
Configure SRM with the ONTAP tools IP address and password using the command: perl command.pl -I <otv-IP> administrator <otv-password>

Due to the requirement to specify a special character in the OTV administrator account password, we should specify the command to be with single quotes around the <otv-password> value.  This ensures that the password gets applied with the special character in the value (especially when the customer uses a "$" at the end of the password) properly.  Otherwise, special characters could be seen by perl as a delimiter of the input and not processed as part of the input value.

perl command.pl -I <otv-IP> administrator ' <otv-password>'

There should also be a note below the sample command to stress surrounding the otv-password value with single quotes.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-jani** [comment]
@DrKeno 
Thank you for contacting us with your feedback. After your inputs are researched internally, we will determine how best to address it and update the content at the earliest.

Thanks,
Jani

**Comment by netapp-jani** [comment]
Step 10 information is corrected, and the issue resolved. Thank you for your feedback.
