### ISSUE TITLE
Configure SRA on the SRM Appliance for OTV/SRA 9.13 

### ISSUE THREAD

**Issue by apordash** [NetAppDocs/ontap-tools-vmware-vsphere#75]
### Page URL

https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/protect/task_configure_sra_on_srm_appliance.html

### Page title

Configure SRA on the SRM Appliance

### Summary

Final step in this doc is incorrect.

10. Configure SRM with the ONTAP tools IP address and password using the command: perl command.pl -I administrator '<otv-password>'

The command should be 'perl command.pl -I <otv_ip> administrator '<otv-password>'

Example of working command:

perl command.pl -I 192.168.0.34 administrator Netapp1!

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-jani** [comment]
@apordash 
Thank you for contacting us with your feedback. After your inputs are researched internally, we will determine how best to address it and update the content at the earliest.

Thanks,
Jani

**Comment by netapp-jani** [comment]
Step 10 information is corrected, and the issue resolved. Thank you for your feedback.
