### ISSUE TITLE
No instructions given

### ISSUE THREAD

**Issue by netapp-bingen** [NetAppDocs/ontap-tools-vmware-vsphere#76]
### Page URL

https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/configure/reference_rebalance_vvols_datastore.html

### Page title

Rebalance vVols datastores

### Summary

Nowhere in the docs can I find actual instructions on how to do this activity.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-jani** [comment]
@netapp-bingen 
Thank you for contacting us with your feedback. After your inputs are researched internally, we will determine how best to address it and update the content at the earliest.

Thanks,
Jani
