### ISSUE TITLE
Request to add a note regarding storing the VM on a vVol datastore

### ISSUE THREAD

**Issue by mojjito** [NetAppDocs/ontap-tools-vmware-vsphere#77]
### Page URL

https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/deploy/task_deploy_ontap_tools.html

### Page title

How to deploy ONTAP tools

### Summary

Please include in a clear manner using a note or similar that as a best practice measure, the OTV VM must **NEVER** be stored on a vVol datastore managed by itself.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-jani** [comment]
@mojjito 
Thank you for contacting us with your feedback. After your inputs are researched internally, we will determine how best to address it and update the content at the earliest.

Thanks,
Jani

**Comment by netapp-jani** [comment]
Thank you for your feedback. Note is added to step 3 in page [How to deploy ONTAP tools](https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/deploy/task_deploy_ontap_tools.html).
