### ISSUE TITLE
Add details about account used to register

### ISSUE THREAD

**Issue by netapp-bingen** [NetAppDocs/ontap-tools-vmware-vsphere#78]
### Page URL

https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/deploy/task_deploy_ontap_tools.html

### Page title

How to deploy ONTAP tools

### Summary

According to engineering, regarding the user credentials used to register the appliance: 
ONTAP tools stores the user details in an encoded format. For any communication from ONTAP toosl to vCenter, these vCenter user details will be used.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-jani** [comment]
@netapp-bingen 

Thank you for contacting us with your feedback. After your inputs are researched internally, we will determine how best to address it and update the content at the earliest.

Thanks,
Jani

**Comment by netapp-jani** [comment]
Step 5 in the [How to deploy ONTAP tools](https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/deploy/task_deploy_ontap_tools.html) page is updated with the requested info.
