### ISSUE TITLE
Typo error How to deploy ONTAP tools page

### ISSUE THREAD

**Issue by Cirff** [NetAppDocs/ontap-tools-vmware-vsphere#79]
### Page URL

https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/deploy/task_deploy_ontap_tools.html

### Page title

How to deploy ONTAP tools

### Summary

Hello found tyoe error on page pl

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by Cirff** [comment]
![Emoji (1)](https://github.com/NetAppDocs/ontap-tools-vmware-vsphere/assets/107471523/7d1ef27e-b249-4795-8cfc-b27e49d52592)

**Comment by netapp-jani** [comment]
@Cirff 
Thank you for contacting us with your feedback. After your inputs are researched internally, we will determine how best to address it and update the content at the earliest.

Thanks,
Jani

**Comment by netapp-jani** [comment]
Thank you for your feedback. We have reviewed the content and edited as required. If you have further feedback, please raise a new issue and we will look into it.
