### ISSUE TITLE
Highlighted commands for step 3 & 4 needs to include "docker" in command highlighting

### ISSUE THREAD

**Issue by DrKeno** [NetAppDocs/ontap-tools-vmware-vsphere#8]
Page: [Configure SRA on the SRM Appliance](https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/protect/task_configure_sra_on_srm_appliance.html)

With step 3, the highlighted command to get the Docker container ID only appears to need to run "ps -l" from the command line.  The highlighted command should be "docker ps -l"

With step 4, the highlighted command should be "docker exec -it -u srm <container id> sh".  Current formatting makes it look like the command to be executed is "exec -it -u srm <container id> sh"

**Comment by Netapp-shabaana** [comment]
Thank you for contacting us with your feedback. After your inputs are researched internally, we will determine how best to address it and update the content at the earliest

**Comment by ntap-bmegan** [comment]
This issue will be closed on tues 30 aug 2022 due to lack of activity within the last 30 days. @DrKeno - If you believe that the original problem persists, please comment in this issue to keep it open for further review.
