### ISSUE TITLE
Addition to port 9083

### ISSUE THREAD

**Issue by mojjito** [NetAppDocs/ontap-tools-vmware-vsphere#80]
### Page URL

https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/deploy/reference_port_requirements_for_vsc.html

### Page title

Port requirements for ONTAP tools

### Summary

Hi Team, hope you are doing well.

Submitting a little addition that is needed for port 9083 - this port needs to be enabled on the firewall from ESXi hosts to the VSC/OTV appliance. I'm bringing this up due to the following KB article that we have:

https://kb.netapp.com/data-mgmt/OTV/VSC_Kbs/vVOL_datastore_created_with_OTV_or_VSC_are_inaccessible_and_show_0B_size

This could be helpful for future customers that are referring to the network port requirements to configure their environments.

Kind Regards,
Mohit Laungani

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-jani** [comment]
Thank you for your feedback. The page [Port requirements for ONTAP tools](https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/deploy/reference_port_requirements_for_vsc.html) is updated with the requested information.
