### ISSUE TITLE
Need a "supported upgrade paths" matrix

### ISSUE THREAD

**Issue by markschuren** [NetAppDocs/ontap-tools-vmware-vsphere#81]
### Page URL

https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/deploy/task_upgrade_to_the_9_8_ontap_tools_for_vmware_vsphere.html

### Page title

Upgrade to the latest release of ONTAP tools

### Summary

We have faced multiple issues following this page. Most of the problems would never have happened, if this documentation would have given information about supported upgrade paths (or at least *recommended* upgrade paths). 

E.g. during upgrading an OTV appliance directly from 9.10 to 9.13P1, we faced multiple major issues, that needed be fixed manually (with various KB articles)... 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-jani** [comment]
@markschuren 
Thank you for contacting us with your feedback. After your inputs are researched internally, we will determine how best to address it and update the content at the earliest.

Thanks,
Jani

**Comment by netapp-jani** [comment]
@markschuren We have provided a link to IMT in the [Upgrade to the latest release of ONTAP tools](https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/deploy/task_upgrade_to_the_9_8_ontap_tools_for_vmware_vsphere.html) page. IMT contains the latest information of all supported paths. Hope this helps.
