### ISSUE TITLE
Can we make it clearer NVMe/FC protocol is for vvol datastores?

### ISSUE THREAD

**Issue by ellen-netapp** [NetAppDocs/ontap-tools-vmware-vsphere#82]
### Page URL

https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/configure/task_provision_datastores.html

### Page title

Provision traditional datastores

### Summary

Received a customer complaint that the documentation is unclear the NVMe/FC protocol is for vvol datastores only. Could we rephrase line "From vSphere 8.0 release, NVMe/FC protocol is supported." to "From vSphere 8.0 release, NVMe/FC protocol is supported for vvol datastores."? Or perhaps something similar to make clear that OTV does not support NVMe/FC for vmfs?

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-jani** [comment]
@ellen-netapp 
Thank you for contacting us with your feedback. After your inputs are researched internally, we will determine how best to address it and update the content at the earliest.

Thanks,
Jani

**Comment by netapp-jani** [comment]
Updated the info 'From vSphere 8.0 release, NVMe/FC protocol is supported for vvol datastores'. Resolving the issue. Thank you for your feedback.
