### ISSUE TITLE
storage.commandTimeout and other SRM settings

### ISSUE THREAD

**Issue by jdwnetapp** [NetAppDocs/ontap-tools-vmware-vsphere#83]
### Page URL

https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/protect/reference_configure_storage_replication_adapter_for_highly_scaled_environment.html

### Page title

Configure Storage Replication Adapter for highly scaled environment

### Summary

Do we really still need to advise customers to set a 99,999 second SRM timeout (essentially 28 hours)?  I realize our OTV appliance struggles with resource contention.  But honestly, after two hours we need to time the operation out and start looking at increasing resources on the appliance, turning off possibly unneeded functionality such as periodic rediscovery, etc.  IMO, advising such a high timeout value is almost an admission of defeat.  It just doesn't reflect well on the product.  I'd suggest simply indicating that if you do hit a timeout, you should consider increasing timeout settings (but not provide a specific 99,999 value).

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-jani** [comment]
@jdwnetapp 
Thank you for contacting us with your feedback. After your inputs are researched internally, we will determine how best to address it and update the content at the earliest.

Thanks,
Jani

**Comment by netapp-jani** [comment]
Thank you for your feedback. Page [Configure Storage Replication Adapter for highly scaled environment](https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/protect/reference_configure_storage_replication_adapter_for_highly_scaled_environment.html) is updated.
