### ISSUE TITLE
Recommended ESXi host and other ONTAP settings

### ISSUE THREAD

**Issue by Tambros** [NetAppDocs/ontap-tools-vmware-vsphere#87]
### Page URL

https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/configure/reference_esxi_host_values_set_by_vsc_for_vmware_vsphere.html

### Page title

ESXi host values set using ONTAP tools

### Summary

The following settings are recommended in the document [.](https://docs.netapp.com/us-en/ontap-apps-dbs/vmware/vmware-vsphere-settings.html). The setting **SunRPC.MaxConnPerIP = 128** is therefore missing in this document.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-jani** [comment]
@Tambros 
Thank you for contacting us with your feedback. After your inputs are researched internally, we will determine how best to address it and update the content at the earliest.

Thanks,
Jani

**Comment by netapp-jani** [comment]
@Tambros 
We have added the requested parameter information to the page - [ESXi host values set using ONTAP tools](https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/configure/reference_esxi_host_values_set_by_vsc_for_vmware_vsphere.html). Thank you for your feedback.
