### ISSUE TITLE
OTV 9.10 is not available on the support site

### ISSUE THREAD

**Issue by apordash** [NetAppDocs/ontap-tools-vmware-vsphere#88]
### Page URL

https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/deploy/task_upgrade_to_the_9_8_ontap_tools_for_vmware_vsphere.html

### Page title

Upgrade to the latest release of ONTAP tools

### Summary

This doc suggests that customers can perform an in-place upgrade to the latest release of ONTAP tools from 9.10 but OTV 9.10 was removed from the NetApp Support Site. OTV 9.12 is the lowest available version. 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by apordash** [comment]
If customer's are running older version such as 9.8 and want to upgrade to 9.13P1, then they will have to do a fresh deployment using the OVA. In place upgrades from 9.8 to 9.13P1 are not supported.

**Comment by netapp-jani** [comment]
@apordash,

Thank you for contacting us with your feedback. After your inputs are researched internally, we will determine how best to address it and update the content at the earliest.

Thanks,
Jani

**Comment by netapp-jani** [comment]
@apordash, ONTAP tools for VMware vSphere 9.10 has reached end of version support and hence it is removed from the support site. The document still contains the information for the customers who are using the old version and would like to upgrade to new version.
