### ISSUE TITLE
What You Will Need section needs more details

### ISSUE THREAD

**Issue by DrKeno** [NetAppDocs/ontap-tools-vmware-vsphere#9]
Page: [Configure SRA on the SRM Appliance](https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/protect/task_configure_sra_on_srm_appliance.html)

We should be providing further details that explains "You should have uploaded the tar.gz file to SRM Appliance."  This should include downloading that file from the NetApp Support site and the steps to upload that file to the SRM Appliance.

**Comment by Netapp-shabaana** [comment]
Thank you for contacting us with your feedback. After your inputs are researched internally, we will determine how best to address it and update the content at the earliest

**Comment by ntap-bmegan** [comment]
This issue will be closed on tues 30 aug 2022 due to lack of activity within the last 30 days. @DrKeno - If you believe that the original problem persists, please comment in this issue to keep it open for further review.
